baseURL = "http://blog.jpl.design"
languageCode = "en-us"
title = "JPL"
theme = "book"

description = "Blog for Peiling Jiang's works."

# githubUsername = "peilingjiang"
BookRepo = "https://github.com/peilingjiang"
tagline = "NYU | IMA | Pei-Ling Jiang"

# BookMenuBundle = '/menu'
BookMenuBundleActiveLinkColor = '\#00d1ff'
BookSearch = true
enableGitInfo = true
